import { prisma } from '@/lib/prisma'
import { notFound } from 'next/navigation'
import { formatDateKey, getDateRangeForDateKey } from '@/lib/date'

interface Props {
    params: Promise<{ date: string }>
}

type ReportMetric = 'change1DayPct' | 'change30DayPct' | 'relativeVolume'

type ReportRow = {
    id: string
    ticker: string
    closingPrice: number
    volume: number
    change1DayPct: number | null
    change30DayPct: number | null
    relativeVolume: number | null
}

export default async function ReportPage(props: Props) {
    const params = await props.params;
    const { date } = params;
    const dateRange = getDateRangeForDateKey(date)

    if (!dateRange) {
        return notFound()
    }

    // Fetch data
    const data = await prisma.priceData.findMany({
        where: {
            date: {
                gte: dateRange.start,
                lt: dateRange.end
            }
        },
        orderBy: {
            ticker: 'asc'
        },
        include: {
            stock: true
        }
    })

    if (data.length === 0) {
        return notFound()
    }

    // Process data for tables
    const gainers = [...data].sort((a, b) => (b.change1DayPct || 0) - (a.change1DayPct || 0)).slice(0, 10)
    const losers = [...data].sort((a, b) => (a.change1DayPct || 0) - (b.change1DayPct || 0)).slice(0, 10)

    const momentum = [...data]
        .filter(item => (item.relativeVolume || 0) > 1.0)
        .sort((a, b) => (b.relativeVolume || 0) - (a.relativeVolume || 0))
        .slice(0, 10)

    const gainers30 = [...data].sort((a, b) => (b.change30DayPct || 0) - (a.change30DayPct || 0)).slice(0, 5)

    return (
        <div className="min-h-screen bg-neutral-950 text-white font-sans p-8 print:p-0">
            <div className="max-w-5xl mx-auto bg-neutral-900 shadow-2xl overflow-hidden border border-neutral-800">

                {/* Header */}
                <header className="px-8 py-8 border-b border-neutral-800 flex justify-between items-end bg-gradient-to-r from-neutral-900 to-neutral-800">
                    <div>
                        <h1 className="text-4xl font-extrabold tracking-tight">
                            <span className="text-white">Flo</span><span className="text-orange-500">Pro</span>
                        </h1>
                        <p className="text-orange-500/80 uppercase tracking-widest text-xs font-semibold mt-1">Equity Insights</p>
                    </div>
                    <div className="text-right">
                        <h2 className="text-2xl font-bold text-gray-200">Daily Market Summary</h2>
                        <p className="text-gray-400 mt-1 font-medium">{formatDateKey(date, 'MMMM do, yyyy')}</p>
                    </div>
                </header>

                <div className="p-8 grid gap-8">

                    {/* Top Row: Gainers & Losers */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <Section title="Top Gainers (Daily)" color="text-green-500">
                            <Table items={gainers} metric="change1DayPct" format="pct" />
                        </Section>

                        <Section title="Top Losers (Daily)" color="text-red-500">
                            <Table items={losers} metric="change1DayPct" format="pct" />
                        </Section>
                    </div>

                    <div className="h-px bg-neutral-800 w-full" />

                    {/* Bottom Row: Momentum & 30D */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <Section title="Momentum Leaders (Rel Vol)" color="text-blue-400">
                            <Table items={momentum} metric="relativeVolume" format="dec" />
                        </Section>

                        <Section title="30-Day Performance" color="text-purple-400">
                            <Table items={gainers30} metric="change30DayPct" format="pct" />
                        </Section>
                    </div>
                </div>

                {/* Footer */}
                <footer className="bg-neutral-950 py-6 text-center border-t border-neutral-800">
                    <p className="text-neutral-500 text-xs uppercase tracking-wide">
                        Generated by FloPro Equity Insights • {new Date().getFullYear()}
                    </p>
                </footer>
            </div>
        </div>
    )
}

function Section({ title, color, children }: { title: string, color: string, children: React.ReactNode }) {
    return (
        <section>
            <h3 className={`text-lg font-bold mb-4 uppercase tracking-wider border-l-4 pl-3 ${color.replace('text-', 'border-')} ${color}`}>
                {title}
            </h3>
            {children}
        </section>
    )
}

function Table({ items, metric, format }: { items: ReportRow[]; metric: ReportMetric; format: 'pct' | 'dec' }) {
    return (
        <div className="overflow-x-auto">
            <table className="w-full text-sm">
                <thead>
                    <tr className="border-b border-neutral-800 text-neutral-400">
                        <th className="pb-2 text-left font-medium">Ticker</th>
                        <th className="pb-2 text-right font-medium">Close</th>
                        <th className="pb-2 text-right font-medium">Vol</th>
                        <th className="pb-2 text-right font-medium">
                            {metric === 'change1DayPct' ? '1D %' :
                                metric === 'change30DayPct' ? '30D %' :
                                    'R.Vol'}
                        </th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-neutral-800/50">
                    {items.map((item) => (
                        <tr key={item.id} className="hover:bg-neutral-800/30 transition-colors">
                            <td className="py-2.5 font-bold text-gray-200">{item.ticker}</td>
                            <td className="py-2.5 text-right text-gray-400">${item.closingPrice.toFixed(2)}</td>
                            <td className="py-2.5 text-right text-gray-500 text-xs">{formatCompactNumber(item.volume)}</td>
                            <td className={`py-2.5 text-right font-bold ${getValueColor(item[metric], metric)}`}>
                                {format === 'pct' ? `${(item[metric] || 0).toFixed(2)}%` : (item[metric] || 0).toFixed(2)}
                            </td>
                        </tr>
                    ))}
                    {items.length === 0 && (
                        <tr><td colSpan={4} className="py-4 text-center text-gray-600 italic">No data</td></tr>
                    )}
                </tbody>
            </table>
        </div>
    )
}

function getValueColor(val: number | null, metric: ReportMetric) {
    if (metric === 'relativeVolume') return 'text-blue-400'
    if ((val || 0) > 0) return 'text-green-500'
    if ((val || 0) < 0) return 'text-red-500'
    return 'text-gray-500'
}

function formatCompactNumber(number: number) {
    return Intl.NumberFormat('en-US', {
        notation: "compact",
        maximumFractionDigits: 1
    }).format(number);
}
